-- 코드를 입력하세요
WITH AI AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
),
AO AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%'
)
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM AI
JOIN AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
