-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i JOIN ANIMAL_OUTS o USING(ANIMAL_ID)
WHERE i.SEX_UPON_INTAKE LIKE 'Intact%' 
      AND (o.SEX_UPON_OUTCOME LIKE 'Spayed%' 
           OR o.SEX_UPON_OUTCOME LIKE 'Neutered%')      
ORDER BY i.ANIMAL_ID        