SELECT C.FLAVOR
FROM
(
    SELECT A.FLAVOR, (A.first_half+B.july) AS total_order
    FROM
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS first_half FROM FIRST_HALF GROUP BY FLAVOR) A
    JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS july FROM JULY GROUP BY FLAVOR) B
    ON A.FLAVOR = B.FLAVOR
    ORDER BY total_order DESC
    LIMIT 3
) C