SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM
(SELECT BS.*, B.CATEGORY FROM BOOK_SALES BS
LEFT JOIN BOOK B
ON BS.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01') A
GROUP BY CATEGORY
ORDER BY CATEGORY ASC