SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE,	I.FAVORITES,
I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS `SCORE`
FROM REST_INFO I JOIN REST_REVIEW R
USING (REST_ID) 
WHERE I.ADDRESS LIKE '서울%' 
GROUP BY I.REST_ID 
HAVING COUNT(*) > 0
ORDER BY 6 DESC, 4 DESC;