WITH RECURSIVE CTE AS(
    SELECT 0 AS `HOUR`
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
)

SELECT T.HOUR, COUNT(ANIMAL_ID) AS `COUNT`
FROM CTE T
LEFT JOIN (SELECT *, HOUR(DATETIME) AS `HOUR`
FROM ANIMAL_OUTS) O
USING (HOUR)
GROUP BY 1
ORDER BY 1;