WITH RECURSIVE T AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR+1 AS H
    FROM T
    WHERE HOUR < 23
)

SELECT T.HOUR, IFNULL(A.COUNT, 0) AS COUNT
FROM T
LEFT JOIN (SELECT HOUR(DATETIME) AS H, COUNT(*) AS COUNT
            FROM ANIMAL_OUTS
            GROUP BY HOUR(DATETIME)) A
ON T.HOUR = A.H