WITH RECURSIVE HOUR_LIST AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOUR_LIST
    WHERE HOUR < 23
)

SELECT
    HL.HOUR,
    IFNULL(COUNT(AO.ANIMAL_ID), 0) AS COUNT
FROM
    HOUR_LIST HL
LEFT JOIN
    ANIMAL_OUTS AO
    ON HOUR(AO.DATETIME) = HL.HOUR
GROUP BY
    HL.HOUR
ORDER BY
    HL.HOUR;
