WITH FIRST AS(
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL),
SECOND AS(
    SELECT ED.ID, ED.PARENT_ID
    FROM ECOLI_DATA AS ED
    JOIN FIRST ON FIRST.ID = ED.PARENT_ID
)
SELECT ECOLI_DATA.ID
FROM ECOLI_DATA
JOIN SECOND ON SECOND.ID = ECOLI_DATA.PARENT_ID