WITH SECOND_G AS (
    SELECT E1.ID ID
    FROM ECOLI_DATA E1
        JOIN ECOLI_DATA E2
            ON E1.PARENT_ID = E2.ID
    WHERE E2.PARENT_ID IS NULL
)

SELECT E.ID
FROM ECOLI_DATA E
    JOIN SECOND_G S
        ON E.PARENT_ID = S.ID
ORDER BY E.ID