/* PERCENT_RANK() 함수 이용 */
SELECT ID, (CASE
    WHEN (PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC))*100 <= 25 THEN 'CRITICAL'
    WHEN (PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC))*100 <= 50 THEN 'HIGH'
    WHEN (PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC))*100 <= 75 THEN 'MEDIUM'
    ELSE 'LOW'
    END) AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY 1;

/* NTILE() 함수 이용 */
SELECT ID, (CASE
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
            ELSE 'LOW'
            END) AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY 1;