SELECT ITEM_ID, ITEM_NAME, RARITY
FROM (SELECT A.ITEM_ID, ITEM_NAME, RARITY, PARENT_ITEM_ID
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B
ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE PARENT_ITEM_ID IS NULL) C
ORDER BY ITEM_ID DESC