SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
    LEFT JOIN ITEM_TREE T
        ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC

-- 처음 풀이
---- 마지막 단계인 아이템 리스트
--WITH LIST AS (
--    SELECT ITEM_ID
--    FROM ITEM_TREE
--    WHERE ITEM_ID NOT IN (
--        SELECT PARENT_ITEM_ID
--        FROM ITEM_TREE
--        WHERE PARENT_ITEM_ID IS NOT NULL
--        GROUP BY PARENT_ITEM_ID
--    )
--)
--
---- 아이템 정보 출력
--SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
--FROM LIST L
--    JOIN ITEM_INFO I
--        ON L.ITEM_ID = I.ITEM_ID
--ORDER BY I.ITEM_ID DESC