SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE*O.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
INNER JOIN (
    SELECT product_id, SUM(amount) as AMOUNT
    FROM food_order
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY product_id
) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;