-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS GE
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT N.ID, N.PARENT_ID, G.GE+1
    FROM ECOLI_DATA N
    JOIN GEN G ON N.PARENT_ID = G.ID
)

SELECT COUNT(ID) AS COUNT , GE AS GENERATION
FROM GEN
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM GEN
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GE