WITH RECURSIVE GENERATION AS (
    SELECT ID
        , PARENT_ID
        , 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID
        , E.PARENT_ID
        , GEN + 1 AS GEN
    FROM ECOLI_DATA E
    JOIN GENERATION G
        ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT
    , GEN AS GENERATION
FROM GENERATION
# 자식이 없다
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM GENERATION WHERE PARENT_ID IS NOT NULL)
GROUP BY GEN;