SELECT ANI_IN.NAME, ANI_IN.DATETIME
FROM ANIMAL_INS AS ANI_IN
         LEFT JOIN ANIMAL_OUTS AS ANI_OUT
                   ON ANI_IN.ANIMAL_ID = ANI_OUT.ANIMAL_ID
WHERE ANI_OUT.ANIMAL_ID IS NULL
ORDER BY ANI_IN.DATETIME LIMIT 3;