SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT T.ITEM_ID
    FROM ITEM_INFO I
    JOIN ITEM_TREE T
    ON T.PARENT_ITEM_ID = I.ITEM_ID
    WHERE I.RARITY = 'RARE')
ORDER BY 1 DESC;