-- 코드를 입력하세요
# SELECT 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
# GROUP BY h.CAR_ID
# HAVING avg()

SELECT h.CAR_ID, ROUND(AVG(DATEDIFF(h.END_DATE, h.START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
GROUP BY h.CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, h.CAR_ID DESC