SELECT ID,
    CASE WHEN RANK_ <= LEN/4 THEN 'CRITICAL'
    WHEN RANK_ <= LEN/2 THEN 'HIGH'
    WHEN RANK_ <= (LEN/4) + (LEN/2) THEN 'MEDIUM'
    ELSE 'LOW'
    END AS `COLONY_NAME`
FROM (SELECT *,
      RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANK_,
      (SELECT COUNT(*) FROM ECOLI_DATA) AS LEN
      FROM ECOLI_DATA) A
ORDER BY ID;