SELECT ID, (
    CASE
    WHEN R*100 <= 25 THEN 'CRITICAL'
    WHEN R*100 <= 50 THEN 'HIGH'
    WHEN R*100 <= 75 THEN 'MEDIUM'
    ELSE 'LOW'
    END) AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS R
    FROM ECOLI_DATA
) E
ORDER BY 1;