SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT(U.USER_ID)) AS 'USERS'
FROM USER_INFO U JOIN ONLINE_SALE S
USING (USER_ID)
GROUP BY 1, 2, 3
HAVING GENDER IS NOT NULL
ORDER BY 1, 2, 3;