SELECT YEAR, MONTH, GENDER, COUNT(USER_ID) AS USERS
FROM (
    SELECT DISTINCT U.USER_ID, GENDER, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM USER_INFO U
    INNER JOIN ONLINE_SALE O
    ON U.USER_ID = O.USER_ID
    WHERE GENDER IS NOT NULL
) T
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;