SELECT YEAR(OS.SALES_DATE) YEAR, MONTH(OS.SALES_DATE) MONTH, UI.GENDER GENDER, COUNT(DISTINCT UI.USER_ID) USERS
FROM ONLINE_SALE OS
    JOIN USER_INFO UI
        ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER
ORDER BY 1, 2, 3