SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS `TOTAL_SALES`
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U
ON U.USER_ID = B.WRITER_ID
WHERE B.STATUS = "DONE"
GROUP BY B.WRITER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY 3;