WITH DONE_USED_GOODS_BOARD AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES, STATUS
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000)

SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM DONE_USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
ORDER BY 3;