SELECT FP.CATEGORY, MP.MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) AS MP ON MP.MAX_PRICE = FP.PRICE AND MP.CATEGORY = FP.CATEGORY
GROUP BY MP.CATEGORY
HAVING MP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MP.MAX_PRICE DESC