SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
JOIN (SELECT *
        FROM SKILLCODES
        WHERE CATEGORY = 'Front End') AS S
    ON D.SKILL_CODE = D.SKILL_CODE|S.CODE
ORDER BY D.ID