SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME FROM SKILLCODES S
JOIN DEVELOPERS D ON (D.SKILL_CODE & S.CODE) IS TRUE
WHERE S.CATEGORY = "Front End"
GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY D.ID;