SELECT USER_ID, NICKNAME, TOTAL_PRICE
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE, STATUS
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) B
JOIN USED_GOODS_USER U
ON WRITER_ID = USER_ID
WHERE TOTAL_PRICE >= 700000
ORDER BY TOTAL_PRICE