-- 코드를 입력하세요
WITH CS AS (SELECT APNT_NO, PT_NO, MDDR_ID, APNT_YMD, MCDP_CD
            FROM APPOINTMENT
            WHERE DATE(APNT_YMD) = '2022-04-13' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS')
,DT AS (SELECT DOCTOR.DR_NAME, CS.APNT_NO, CS.PT_NO, CS.MDDR_ID, CS.APNT_YMD, CS.MCDP_CD
        FROM DOCTOR
        JOIN CS ON CS.MDDR_ID = DOCTOR.DR_ID)

SELECT DT.APNT_NO, PT_NAME, PATIENT.PT_NO, DT.MCDP_CD, DT.DR_NAME, DT.APNT_YMD
FROM PATIENT
JOIN DT ON PATIENT.PT_NO = DT.PT_NO
ORDER BY DT.APNT_YMD