SELECT ROUTE,
    CONCAT(CONVERT(ROUND(SUM(D_BETWEEN_DIST), 1), CHAR), 'km') AS 'TOTAL_DISTANCE',
    CONCAT(CONVERT(ROUND(AVG(D_BETWEEN_DIST), 2), CHAR), 'km') AS 'AVERAGE_DISTANCE'
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;