SELECT CART_ID
FROM CART_PRODUCTS
--WHERE NAME IN ('Yogurt', 'Milk')
GROUP BY CART_ID
HAVING GROUP_CONCAT(NAME) LIKE '%Milk%' AND GROUP_CONCAT(NAME) LIKE '%Yogurt%'
ORDER BY CART_ID

-- HAVING COUNT(DISTINCT NAME) = 2 도 가능
-- DISTINCT 알아두자