SELECT CAR_ID, IF(CNT > 0, '대여중', '대여 가능') AS AVAILABILITY
FROM (
    SELECT CAR_ID,
        SUM(IF(START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16', 1, 0))
        AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
) AS C
ORDER BY CAR_ID DESC;
