SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    C.FEE
FROM (
    SELECT
        B.CAR_ID,
        B.CAR_TYPE,
        ROUND(B.DAILY_FEE * 30 * ((100 - IFNULL(D.DISCOUNT_RATE, 0)) * 0.01)) AS FEE
    FROM
        CAR_RENTAL_COMPANY_CAR B
    LEFT JOIN
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON B.CAR_TYPE = D.CAR_TYPE
    WHERE
        B.CAR_TYPE IN ('SUV', '세단')
        AND B.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE (END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
        )
        AND (D.DURATION_TYPE LIKE '30%' OR D.DURATION_TYPE IS NULL)
    GROUP BY
        B.CAR_ID, B.CAR_TYPE, B.DAILY_FEE, D.DISCOUNT_RATE
    HAVING
        FEE BETWEEN 500000 AND 2000000
) C
ORDER BY
    C.FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;