WITH L AS (
    SELECT H.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE, DATEDIFF(END_DATE, START_DATE)+1 AS DIFF, CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상'
            ELSE '할인없음' END AS DISCOUNT
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT L.HISTORY_ID, ROUND(DAILY_FEE*(100-IFNULL(DISCOUNT_RATE, 0))*0.01*DIFF) AS FEE
FROM L
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON L.CAR_TYPE = P.CAR_TYPE AND L.DISCOUNT = P.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC;