SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;

/*
DATEDIFF: 날짜 차이구하기
1) DATEDIFF(날짜1, 날짜2): 날짜1 - 날짜2
2) TIMESTAMPDIFF(단위, 날짜1, 날짜2): 날짜2 - 날짜1
*/
