SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
USING (CAR_ID)
WHERE C.CAR_TYPE = '세단' AND DATE_FORMAT(H.START_DATE,'%m') = 10
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;