SELECT
    CASE
        WHEN SUM(CASE WHEN S.NAME = 'Python' AND (S.CODE & D.SKILL_CODE) = S.CODE THEN 1 ELSE 0 END) > 0
             AND SUM(CASE WHEN S.CATEGORY = 'Front End' AND (S.CODE & D.SKILL_CODE) = S.CODE THEN 1 ELSE 0 END) > 0
             THEN 'A'
        WHEN SUM(CASE WHEN S.NAME = 'C#' AND (S.CODE & D.SKILL_CODE) = S.CODE THEN 1 ELSE 0 END) > 0
             THEN 'B'
        WHEN SUM(CASE WHEN S.CATEGORY = 'Front End' AND (S.CODE & D.SKILL_CODE) = S.CODE THEN 1 ELSE 0 END) > 0
             THEN 'C'
        ELSE NULL
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
LEFT JOIN SKILLCODES S ON (S.CODE & D.SKILL_CODE) = S.CODE
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, D.ID;