-- bit 연산으로 포함된 거 찾고 싶으면 &와 sum 사용
-- CASE WHEN THE END 활용하기
-- WHERE는 SELECT 전, HAVING은 SELECT 후 연산 이루어짐

SELECT
    CASE
        WHEN SKILL_CODE&(SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY='Front End')
            AND SKILL_CODE& (SELECT CODE FROM SKILLCODES WHERE NAME = 'python')
        THEN 'A'
        WHEN SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
        THEN 'B'
        WHEN SKILL_CODE&(SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY='Front End')
        THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID