-- 코드를 입력하세요
WITH CARS AS(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT MONTH(CH.START_DATE) AS MONTH, CH.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
JOIN CARS ON CH.CAR_ID = CARS.CAR_ID
WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
GROUP BY MONTH(CH.START_DATE), CH.CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH, CH.CAR_ID DESC

