WITH RENTAL_SUM AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE > '2022-07-31' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE > '2022-07-31' AND START_DATE < '2022-11-01' AND CAR_ID IN (SELECT * FROM RENTAL_SUM)
GROUP BY CAR_ID, MONTH(START_DATE)
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC