SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS `REVIEW_DATE`
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
USING (MEMBER_ID)
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID 
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC;