SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW
INNER JOIN (
    SELECT R.MEMBER_ID, MEMBER_NAME
    FROM MEMBER_PROFILE M
    INNER JOIN (
        SELECT MEMBER_ID
        FROM (
            SELECT DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS REVIEW_COUNT, MEMBER_ID
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS REVEW_COUNT
        WHERE REVIEW_COUNT = 1
    ) R
    ON M.MEMBER_ID = R.MEMBER_ID
) R
ON R.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;