-- 코드를 입력하세요
WITH U AS (SELECT WRITER_ID
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3)

SELECT UGU.USER_ID, UGU.NICKNAME,
        CONCAT(UGU.CITY, " ", UGU.STREET_ADDRESS1, " ", UGU.STREET_ADDRESS2) AS '전체주소',
        CONCAT(SUBSTR(UGU.TLNO,1,3),'-',SUBSTR(UGU.TLNO,4,4),'-',SUBSTR(UGU.TLNO,8,4)) AS '전화번호'
FROM USED_GOODS_USER AS UGU
JOIN U ON U.WRITER_ID = UGU.USER_ID
ORDER BY UGU.USER_ID DESC