-- 코드를 작성해주세요
WITH CC AS (
    SELECT PARENT_ID, COUNT(*) AS CNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)
SELECT ID, IFNULL(CC.CNT,0) AS CHILD_COUNT
FROM ECOLI_DATA AS ED
LEFT JOIN CC ON CC.PARENT_ID = ED.ID