SELECT
    YEAR,
    MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM (
    SELECT
        YEAR(A.SALES_DATE) AS YEAR,
        MONTH(A.SALES_DATE) AS MONTH,
        A.USER_ID
    FROM
        ONLINE_SALE A
    JOIN
        (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021) B
    ON
        A.USER_ID = B.USER_ID
) A
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;