SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A
JOIN (
    SELECT B.AUTHOR_ID, CATEGORY, (PRICE * SALES) AS TOTAL_SALES, SALES_DATE
    FROM BOOK B
    JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
) B
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE YEAR(B.SALES_DATE) = 2022 AND MONTH(B.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC;