SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30) `FEE`
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE 
AND D.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
) 
AND FLOOR(C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30) BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2, 1 DESC;