WITH AVAILABLE_CAR AS (
    SELECT DISTINCT C.CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE IN ('SUV', '세단')
    AND H.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE START_DATE < '2022-12-01' AND END_DATE >= '2022-11-01')

    ORDER BY CAR_ID),
    COST AS (
        SELECT CAR_TYPE, (100-DISCOUNT_RATE)*0.01 AS DISCOUNT_FEE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE IN ('SUV', '세단')
        AND DURATION_TYPE LIKE '30%'
    )

SELECT CAR_ID, A.CAR_TYPE, ROUND(DAILY_FEE*30*DISCOUNT_FEE) AS FEE
FROM AVAILABLE_CAR A
JOIN COST C
ON A.CAR_TYPE = C.CAR_TYPE
WHERE DAILY_FEE*30*DISCOUNT_FEE >= 500000 AND DAILY_FEE*30*DISCOUNT_FEE < 2000000
ORDER BY 3 DESC, 2, 1 DESC;

